# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VodSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'GenseeSDK/GSVodSDK', '~>1.1.5'
  # Pods for VodSDKDemo

end
